server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8  
spring:
  datasource:
    url: jdbc:mysql://bdm2928079.my3w.com:3306/bdm2928079_db?characterEncoding=UTF-8
    username: bdm2928079
    password: XXXX
    driver-class-name: com.mysql.jdbc.Driver

